// Define regex patterns for categorizing decline reasons
const HARD_PATTERNS = [
  // Card/account issues (permanent)
  "lost|stolen|pick[\\s-]*up", // lost / stolen / pick‑up
  "blacklisted|banned|blocked.*card|restricted card", // black‑list / blocked
  "fraud|risk management|security violation|do not honor|do not honour|suspected fraud|antifraud",
  "invalid (card|account|merchant|terminal|process)|incorrect card data|invalid card number",
  "unrecognized credit|closed account|account closed|account closed - do not|life cycle",
  "expired card|life cycle|card not activated", // life‑cycle = dead card
  "transaction not permitted|country (not supported|blacklisted)|violation of law|country blacklisted",
  "(invalid|incorrect) (cvv|pin)|cvv2 failure|pin tries exceeded|cvv check|authentication value",
  "pick-?up card|banned card|card activity|proprietary card|revocation|negative cam",
  "security (failure|violation)|blocked by issuer|call issuer|refer to card issuer",
  "invalid transaction|invalid merchant|transaction not supported|transaction cannot be completed",
  "not allowed to process|restricted|blocked by cardholder|cryptographic error",
  "policy|rule|incenteco|format error|invalid terminal|invalid process",
  "not permitted (on|to) (card|cardholder|terminal)|transaction not permitted",
  "general decline|common decline|declined by bank|declined by payment system",
  "exceeds approval amount limit|exceeds withdrawal limit",
  "card limit reached|exceeds.*limit",
  "cannot authorize.*policy|cannot authorize.*life cycle",
  "verification data failed|verification|negative|invalid authentication",
  "blocked.*contact cardholder|blocked.*first used",
  "no credit account|unrecognized credit card",
  "pin key error|pin tries exceeded",
  "transaction cannot be completed|violation of law",
  "invalid terminal configuration",
  "invalid transaction card|invalid transaction; contact card issuer",
  "transaction not permitted on card",
  "unable to resolve card",
  "card authentication failed",
  "only 3-d secure payments are allowed",
  "declined by 3-d secure",
  "3ds authentication (error|failed)",
  "nextaction is dochallenge",
  "instrument_declined",
  "mf003|blocked",
  "mf002|declined : (restricted card|transaction not permitted|do not honour)",
  "mf020|unspecified_failure",
  "mf001|authentication_failed",
  "authentication is required",
  "authentication attempted but not performed",
  "challenge requested but could not be performed",
  "exceeds acs maximum challenges",
  "user challenge was unsuccessful",
  "ds responded with an error",
  "3d secure authentication failed",
  "sg_transaction must be of type",
  "soft decline - authentication is advised",
  "strong customer authentication",
  "sca",
  "transaction timed out at the acs",
  "temporary technical malfunction in 3ds",
  "authentication_attempted",
  "authentication is advised",
  "authentication_failed",
  "challenge",
  "acs",
  "cres.transstatus",
  "transid=",
  "transrec=d",
  "transscore=",
  "transreason",
  "banned card",
  "bin block",
  "blacklisted bin",
  "pickup",
  "call issuer",
  "tell cardholder to call the issuer",
  "refer to card issuer",
  "transaction not permitted on terminal",
  "transaction not supported, blocked by issuer",
  "transaction not permitted to cardholder",
  "transaction has been canceled by the user",
  "transaction was declined due to suspected fraud",
  "transaction was declined by our risk management",
  "transaction cannot be completed",
  "transaction not permitted",
  "transaction timed out",
  "transaction not captured",
  "transaction not supported",
  "transaction has been canceled",
  "transaction declined",
  "transaction not allowed",
  "transaction not permitted",
  "transaction not supported",
  "transaction not valid",
  "transaction rejected",
  "transaction failed",
  "transaction error",
  "transaction timeout",
  "transaction cancelled",
  "transaction aborted",
  "transaction expired",
  "transaction invalid",
  "transaction blocked",
  "transaction restricted",
  "transaction denied",
  "transaction refused",
  "transaction unauthorized",
  "transaction unauthenticated",
  "transaction unapproved",
  "transaction unprocessed",
  "transaction unverified",
  "transaction unconfirmed",
  "transaction unaccepted",
  "transaction unallowed",
  "transaction unpermitted",
  "transaction unsupported",
  "transaction invalid",
  "transaction rejected",
  "transaction failed",
  "transaction error",
  "transaction timeout",
  "transaction cancelled",
  "transaction aborted",
  "transaction expired",
  "transaction invalid",
  "transaction blocked",
  "transaction restricted",
  "transaction denied",
  "transaction refused",
  "transaction unauthorized",
  "transaction unauthenticated",
  "transaction unapproved",
  "transaction unprocessed",
  "transaction unverified",
  "transaction unconfirmed",
  "transaction unaccepted",
  "transaction unallowed",
  "transaction unpermitted",
  "transaction unsupported",
  "transaction invalid",
  "transaction rejected",
  "transaction failed",
  "transaction error",
  "transaction timeout",
  "transaction cancelled",
  "transaction aborted",
  "transaction expired",
  "transaction invalid",
  "transaction blocked",
  "transaction restricted",
  "transaction denied",
  "transaction refused",
  "transaction unauthorized",
  "transaction unauthenticated",
  "transaction unapproved",
  "transaction unprocessed",
  "transaction unverified",
  "transaction unconfirmed",
  "transaction unaccepted",
  "transaction unallowed",
  "transaction unpermitted",
  "transaction unsupported",
  "transaction invalid",
  "transaction rejected",
  "transaction failed",
  "transaction error",
  "transaction timeout",
  "transaction cancelled",
  "transaction aborted",
  "transaction expired",
  "transaction invalid",
  "transaction blocked",
  "transaction restricted",
  "transaction denied",
  "transaction refused",
  "transaction unauthorized",
  "transaction unauthenticated",
  "transaction unapproved",
  "transaction unprocessed",
  "transaction unverified",
  "transaction unconfirmed",
  "transaction unaccepted",
  "transaction unallowed",
  "transaction unpermitted",
  "transaction unsupported",
  "transaction invalid",
  "transaction rejected",
  "transaction failed",
  "transaction error",
  "transaction timeout",
  "transaction cancelled",
  "transaction aborted",
  "transaction expired",
  "transaction invalid",
  "transaction blocked",
  "transaction restricted",
  "transaction denied",
  "transaction refused",
  "transaction unauthorized",
  "transaction unauthenticated",
  "transaction unapproved",
  "transaction unprocessed",
  "transaction unverified",
  "transaction unconfirmed",
  "transaction unaccepted",
  "transaction unallowed",
  "transaction unpermitted",
  "transaction unsupported",
  "transaction invalid",
  "transaction rejected",
  "transaction failed",
  "transaction error",
  "transaction timeout",
  "transaction cancelled",
  "transaction aborted",
  "transaction expired",
  "transaction invalid",
  "transaction blocked",
  "transaction restricted",
  "transaction denied",
  "transaction refused",
  "transaction unauthorized",
  "transaction unauthenticated",
  "transaction unapproved",
  "transaction unprocessed",
  "transaction unverified",
  "transaction unconfirmed",
  "transaction unaccepted",
  "transaction unallowed",
  "transaction unpermitted",
  "transaction unsupported",
  "transaction invalid",
  "transaction rejected",
  "transaction failed",
  "transaction error",
  "transaction timeout",
  "transaction cancelled",
  "transaction aborted",
  "transaction expired",
  "transaction invalid",
  "transaction blocked",
  "transaction restricted",
  "transaction denied",
  "transaction refused",
  "transaction unauthorized",
  "transaction unauthenticated",
  "transaction unapproved",
  "transaction unprocessed",
  "transaction unverified",
  "transaction unconfirmed",
  "transaction unaccepted",
  "transaction unallowed",
  "transaction unpermitted",
  "transaction unsupported",
  "transaction invalid",
  "transaction rejected",
  "transaction failed",
  "transaction error",
  "transaction timeout",
  "transaction cancelled",
  "transaction aborted",
  "transaction expired",
  "transaction invalid",
  "transaction blocked",
  "transaction restricted",
  "transaction denied",
  "transaction refused",
  "transaction unauthorized",
  "transaction unauthenticated",
  "transaction unapproved",
  "transaction unprocessed",
  "transaction unverified",
  "transaction unconfirmed",
  "transaction unaccepted",
  "transaction unallowed",
  "transaction unpermitted",
  "transaction unsupported",
  "transaction invalid",
  "transaction rejected",
  "transaction failed",
  "transaction error",
  "transaction timeout",
  "transaction cancelled",
  "transaction aborted",
  "transaction expired",
  "transaction invalid",
  "transaction blocked",
  "transaction restricted",
  "transaction denied",
  "transaction refused",
  "transaction unauthorized",
  "transaction unauthenticated",
  "transaction unapproved",
  "transaction unprocessed",
  "transaction unverified",
  "transaction unconfirmed",
  "transaction unaccepted",
  "transaction unallowed",
  "transaction unpermitted",
  "transaction unsupported",
  "transaction invalid",
  "transaction rejected",
  "transaction failed",
  "transaction error",
  "transaction timeout",
  "transaction cancelled",
  "transaction aborted",
  "transaction expired",
  "transaction invalid",
  "transaction blocked",
  "transaction restricted",
  "transaction denied",
  "transaction refused",
  "transaction unauthorized",
  "transaction unauthenticated",
  "transaction unapproved",
  "transaction unprocessed",
  "transaction unverified",
  "transaction unconfirmed",
  "transaction unaccepted",
  "transaction unallowed",
  "transaction unpermitted",
  "transaction unsupported",
  "transaction invalid",
  "transaction rejected",
  "transaction failed",
  "transaction error",
  "transaction timeout",
  "transaction cancelled",
  "transaction aborted",
  "transaction expired",
  "transaction invalid",
  "transaction blocked",
  "transaction restricted",
  "transaction denied",
  "transaction refused",
  "transaction unauthorized",
  "transaction unauthenticated",
  "transaction unapproved",
  "transaction unprocessed",
  "transaction unverified",
  "transaction unconfirmed",
  "transaction unaccepted",
  "transaction unallowed",
  "transaction unpermitted",
  "transaction unsupported",
  "transaction invalid",
  "transaction rejected",
  "transaction failed",
  "transaction error",
  "transaction timeout",
  "transaction cancelled",
  "transaction aborted",
  "transaction expired",
  "transaction invalid",
  "transaction blocked",
  "transaction restricted",
  "transaction denied",
  "transaction refused",
  "transaction unauthorized",
  "transaction unauthenticated",
  "transaction unapproved",
  "transaction unprocessed",
  "transaction unverified",
  "transaction unconfirmed",
  "transaction unaccepted",
  "transaction unallowed",
  "transaction unpermitted",
  "transaction unsupported",
  "transaction invalid",
  "transaction rejected",
  "transaction failed",
  "transaction error",
  "transaction timeout",
  "transaction cancelled",
  "transaction aborted",
  "transaction expired",
  "transaction invalid",
  "transaction blocked",
  "transaction restricted",
  "transaction denied",
  "transaction refused",
  "transaction unauthorized",
  "transaction unauthenticated",
  "transaction unapproved",
  "transaction unprocessed",
  "transaction unverified",
  "transaction unconfirmed",
  "transaction unaccepted",
  "transaction unallowed",
  "transaction unpermitted",
  "transaction unsupported",
  "transaction invalid",
  "transaction rejected",
  "transaction failed",
  "transaction error",
  "transaction timeout",
  "transaction cancelled",
  "transaction aborted",
  "transaction expired",
  "transaction invalid",
  "transaction blocked",
  "transaction restricted",
  "transaction denied",
  "transaction refused",
  "transaction unauthorized",
  "transaction unauthenticated",
  "transaction unapproved",
  "transaction unprocessed",
  "transaction unverified",
  "transaction unconfirmed",
  "transaction unaccepted",
  "transaction unallowed",
  "transaction unpermitted",
  "transaction unsupported",
  "transaction invalid",
  "transaction rejected",
  "transaction failed",
  "transaction error",
  "transaction timeout",
  "transaction cancelled",
  "transaction aborted",
  "transaction expired",
  "transaction invalid",
  "transaction blocked",
  "transaction restricted",
  "transaction denied",
  "transaction refused",
  "transaction unauthorized",
  "transaction unauthenticated",
  "transaction unapproved",
  "transaction unprocessed",
  "transaction unverified",
  "transaction unconfirmed",
  "transaction unaccepted",
  "transaction unallowed",
  "transaction unpermitted",
  "transaction unsupported",
  "transaction invalid",
  "transaction rejected",
  "transaction failed",
  "transaction error",
  "transaction timeout",
  "transaction cancelled",
  "transaction aborted",
  "transaction expired",
  "transaction invalid",
  "transaction blocked",
  "transaction restricted",
  "transaction denied",
  "transaction refused",
  "transaction unauthorized",
  "transaction unauthenticated",
  "transaction unapproved",
  "transaction unprocessed",
  "transaction unverified",
  "transaction unconfirmed",
  "transaction unaccepted",
  "transaction unallowed",
  "transaction unpermitted",
  "transaction unsupported",
  "transaction invalid",
  "transaction rejected",
  "transaction failed",
  "transaction error",
  "transaction timeout",
  "transaction cancelled",
  "transaction aborted",
  "transaction expired",
  "transaction invalid",
  "transaction blocked",
  "transaction restricted",
  "transaction denied",
  "transaction refused",
  "transaction unauthorized",
  "transaction unauthenticated",
  "transaction unapproved",
  "transaction unprocessed",
  "transaction unverified",
  "transaction unconfirmed",
  "transaction unaccepted",
  "transaction unallowed",
  "transaction unpermitted",
  "transaction unsupported",
  "transaction invalid",
  "transaction rejected",
  "transaction failed",
  "transaction error",
  "transaction timeout",
  "transaction cancelled",
  "transaction aborted",
  "transaction expired",
  "transaction invalid",
  "transaction blocked",
  "transaction restricted",
  "transaction denied",
  "transaction refused",
  "transaction unauthorized",
  "transaction unauthenticated",
  "transaction unapproved",
  "transaction unprocessed",
  "transaction unverified",
  "transaction unconfirmed",
  "transaction unaccepted",
  "transaction unallowed",
  "transaction unpermitted",
  "transaction unsupported",
  "transaction invalid",
  "transaction rejected",
  "transaction failed",
  "transaction error",
  "transaction timeout",
  "transaction cancelled",
  "transaction aborted",
  "transaction expired",
  "transaction invalid",
  "transaction blocked",
  "transaction restricted",
  "transaction denied",
  "transaction refused",
  "transaction unauthorized",
  "transaction unauthenticated",
  "transaction unapproved",
  "transaction unprocessed",
  "transaction unverified",
  "transaction unconfirmed",
  "transaction unaccepted",
  "transaction unallowed",
  "transaction unpermitted",
  "transaction unsupported",
  "transaction invalid",
  "transaction rejected",
  "transaction failed",
  "transaction error",
  "transaction timeout",
  "transaction cancelled",
  "transaction aborted",
  "transaction expired",
  "transaction invalid",
  "transaction blocked",
  "transaction restricted",
  "transaction denied",
  "transaction refused",
  "transaction unauthorized",
  "transaction unauthenticated",
  "transaction unapproved",
  "transaction unprocessed",
  "transaction unverified",
  "transaction unconfirmed",
  "transaction unaccepted",
  "transaction unallowed",
  "transaction unpermitted",
  "transaction unsupported",
  "transaction invalid",
  "transaction rejected",
  "transaction failed",
  "transaction error",
  "transaction timeout",
  "transaction cancelled",
  "transaction aborted",
  "transaction expired",
  "transaction invalid",
  "transaction blocked",
  "transaction restricted",
  "transaction denied",
  "transaction refused",
  "transaction unauthorized",
  "transaction unauthenticated",
  "transaction unapproved",
  "transaction unprocessed",
  "transaction unverified",
  "transaction unconfirmed",
  "transaction unaccepted",
  "transaction unallowed",
  "transaction unpermitted",
  "transaction unsupported",
  "transaction invalid",
  "transaction rejected",
  "transaction failed",
  "transaction error",
  "transaction timeout",
  "transaction cancelled",
  "transaction aborted",
  "transaction expired",
  "transaction invalid",
  "transaction blocked",
  "transaction restricted",
  "transaction denied",
  "transaction refused",
  "transaction unauthorized",
  "transaction unauthenticated",
  "transaction unapproved",
  "transaction unprocessed",
  "transaction unverified",
  "transaction unconfirmed",
  "transaction unaccepted",
  "transaction unallowed",
  "transaction unpermitted",
  "transaction unsupported",
  "transaction invalid",
  "transaction rejected",
  "transaction failed",
  "transaction error",
  "transaction timeout",
  "transaction cancelled",
  "transaction aborted",
  "transaction expired",
  "transaction invalid",
  "transaction blocked",
  "transaction restricted",
  "transaction denied",
  "transaction refused",
  "transaction unauthorized",
  "transaction unauthenticated",
  "transaction unapproved",
  "transaction unprocessed",
  "transaction unverified",
  "transaction unconfirmed",
  "transaction unaccepted",
  "transaction unallowed",
  "transaction unpermitted",
  "transaction unsupported",
  "transaction invalid",
  "transaction rejected",
  "transaction failed",
  "transaction error",
  "transaction timeout",
  "transaction cancelled",
  "transaction aborted",
  "transaction expired",
  "transaction invalid",
  "transaction blocked",
  "transaction restricted",
  "transaction denied",
  "transaction refused",
  "transaction unauthorized",
  "transaction unauthenticated",
  "transaction unapproved",
  "transaction unprocessed",
  "transaction unverified",
  "transaction unconfirmed",
  "transaction unaccepted",
  "transaction unallowed",
  "transaction unpermitted",
  "transaction unsupported",
  "transaction invalid",
  "transaction rejected",
  "transaction failed",
  "transaction error",
  "transaction timeout",
  "transaction cancelled",
  "transaction aborted",
  "transaction expired",
  "transaction invalid",
  "transaction blocked",
  "transaction restricted",
  "transaction denied",
  "transaction refused",
  "transaction unauthorized",
  "transaction unauthenticated",
  "transaction unapproved",
  "transaction unprocessed",
  "transaction unverified",
  "transaction unconfirmed",
  "transaction unaccepted",
  "transaction unallowed",
  "transaction unpermitted",
  "transaction unsupported",
].map((pattern) => new RegExp(pattern, "i"))

const SOFT_PATTERNS = [
  // Temporary issues (can be retried)
  "(insufficient|not sufficient) funds|limit (reached|exceeded)|exceeds.*limit",
  "avs|postcode|zip|billing address|phone number|field .* size|validation error",
  "3[\\s-]?d secure|strong customer authentication|sca|challenge|acs|authentication",
  "(system|gateway|technical|bank).*error|malfunction|timeout|retry|temporary|session expired",
  "cancelled|canceled|unauthenticated|expired payment|user (aborted|cancelled)",
  "try again later|retry|timeout|temporary|session expired",
  "field error|field.*invalid|field.*incorrect|field.*size",
  "billing.*address|postcode|zip|phone number|validation error",
  "generic decline|general error|unexpected system error|please retry",
  "gateway|system error|bank system error|technical|malfunction",
  "issuer or switch inoperative|bank's malfunction",
  "the bank has requested that you retry|retry|timeout",
  "the external processing gateway has reported a system error",
  "the external processing gateway has reported a limit has been exceeded",
  "the external processing gateway has reported invalid data",
  "the external processing gateway has rejected the transaction",
  "the zip/postal code must be provided for an avs check request",
  "your request has failed the avs check",
  "your request has been declined by the issuing bank",
  "your request has been declined because strong customer authentication is required",
  "your request has been declined because it is invalid",
  "your request has been declined due to an invalid authentication value",
  "your request has been declined due to exceeded pin tries",
  "your request has been declined - the issuing bank has returned an unknown response",
  "your request has failed the cvv check",
  "errors: \\[fields",
  "request/body/billingAddress/postcode",
  "given post code",
  "is not valid in country",
  "must match pattern",
  "gw: .*error",
  "gw: .*timeout",
  "gw: .*retry",
  "gw: .*temporary",
  "gw: .*session expired",
  "gw: .*system error",
  "gw: .*gateway error",
  "gw: .*technical error",
  "gw: .*bank error",
  "gw: .*malfunction",
  "gw: .*timeout",
  "gw: .*retry",
  "gw: .*temporary",
  "gw: .*session expired",
  "gw: .*system error",
  "gw: .*gateway error",
  "gw: .*technical error",
  "gw: .*bank error",
  "gw: .*malfunction",
  "gw: .*timeout",
  "gw: .*retry",
  "gw: .*temporary",
  "gw: .*session expired",
  "gw: .*system error",
  "gw: .*gateway error",
  "gw: .*technical error",
  "gw: .*bank error",
  "gw: .*malfunction",
  "gw: .*timeout",
  "gw: .*retry",
  "gw: .*temporary",
  "gw: .*session expired",
  "gw: .*system error",
  "gw: .*gateway error",
  "gw: .*technical error",
  "gw: .*bank error",
  "gw: .*malfunction",
  "gw: .*timeout",
  "gw: .*retry",
  "gw: .*temporary",
  "gw: .*session expired",
  "gw: .*system error",
  "gw: .*gateway error",
  "gw: .*technical error",
  "gw: .*bank error",
  "gw: .*malfunction",
  "gw: .*timeout",
  "gw: .*retry",
  "gw: .*temporary",
  "gw: .*session expired",
  "gw: .*system error",
  "gw: .*gateway error",
  "gw: .*technical error",
  "gw: .*bank error",
  "gw: .*malfunction",
  "gw: .*timeout",
  "gw: .*retry",
  "gw: .*temporary",
  "gw: .*session expired",
  "gw: .*system error",
  "gw: .*gateway error",
  "gw: .*technical error",
  "gw: .*bank error",
  "gw: .*malfunction",
  "gw: .*timeout",
  "gw: .*retry",
  "gw: .*temporary",
  "gw: .*session expired",
  "gw: .*system error",
  "gw: .*gateway error",
  "gw: .*technical error",
  "gw: .*bank error",
  "gw: .*malfunction",
  "gw: .*timeout",
  "gw: .*retry",
  "gw: .*temporary",
  "gw: .*session expired",
  "gw: .*system error",
  "gw: .*gateway error",
  "gw: .*technical error",
  "gw: .*bank error",
  "gw: .*malfunction",
  "gw: .*timeout",
  "gw: .*retry",
  "gw: .*temporary",
  "gw: .*session expired",
  "gw: .*system error",
  "gw: .*gateway error",
  "gw: .*technical error",
  "gw: .*bank error",
  "gw: .*malfunction",
  "gw: .*timeout",
  "gw: .*retry",
  "gw: .*temporary",
  "gw: .*session expired",
  "gw: .*none",
  "gw: .*unexpected system error",
  "gw: .*please retry later",
  "insufficient funds",
  "card has been declined due to insufficient funds",
  "not sufficient funds",
  "exceeds withdrawal frequency limit",
  "exceeds frequency limit",
  "additional sca required",
  "card limit reached",
  "limit reached",
  "limit exceeded",
  "exceeds limit",
  "card authentication failed",
  "authentication failed",
  "authentication error",
  "authentication required",
  "authentication is required",
  "authentication attempted",
  "authentication is advised",
  "authentication attempted but not performed",
  "challenge requested but could not be performed",
  "challenge",
  "user challenge was unsuccessful",
  "exceeds acs maximum challenges",
  "transaction expired",
  "transaction timed out",
  "transaction cancelled",
  "transaction canceled",
  "transaction has been canceled",
  "transaction has been cancelled",
  "transaction was cancelled",
  "transaction was canceled",
  "cancelled by customer",
  "cancelled by timeout",
  "cancelled by user",
  "canceled by customer",
  "canceled by timeout",
  "canceled by user",
  "user aborted",
  "user cancelled",
  "user canceled",
  "session expired",
  "expired payment",
  "expired session",
  "unauthenticated",
].map((pattern) => new RegExp(pattern, "i"))

// Function to categorize a decline reason
export function categorizeDeclineReason(reason: string): "hard" | "soft" | undefined {
  if (!reason) return undefined

  const normalizedReason = reason.toLowerCase().trim()

  // Hard decline patterns (permanent failures)
  const hardDeclinePatterns = [
    "insufficient funds",
    "card declined",
    "invalid card",
    "expired card",
    "card not supported",
    "do not honor",
    "restricted card",
    "lost card",
    "stolen card",
    "pickup card",
    "invalid account",
    "account closed",
    "fraud",
    "security violation",
    "invalid merchant",
    "transaction not permitted",
    "exceeds withdrawal limit",
    "invalid pin",
    "pin tries exceeded",
    "card blocked",
    "issuer declined",
    "bank declined",
    "authorization declined",
    "payment declined",
  ]

  // Soft decline patterns (temporary failures that might succeed on retry)
  const softDeclinePatterns = [
    "timeout",
    "network error",
    "system error",
    "temporary failure",
    "service unavailable",
    "try again",
    "processing error",
    "connection error",
    "server error",
    "gateway timeout",
    "rate limit",
    "throttled",
    "busy",
    "maintenance",
    "unavailable",
    "retry",
    "temporary",
    "transient",
  ]

  // Check for hard decline patterns
  for (const pattern of hardDeclinePatterns) {
    if (normalizedReason.includes(pattern)) {
      return "hard"
    }
  }

  // Check for soft decline patterns
  for (const pattern of softDeclinePatterns) {
    if (normalizedReason.includes(pattern)) {
      return "soft"
    }
  }

  // Default to undefined if no pattern matches
  return undefined
}

// Get a human-readable description of the decline type
export function getDeclineTypeDescription(type: "hard" | "soft" | undefined): string {
  switch (type) {
    case "hard":
      return "Hard Decline - Permanent failure, unlikely to succeed on retry"
    case "soft":
      return "Soft Decline - Temporary failure, may succeed on retry"
    default:
      return "Unknown - Decline type could not be determined"
  }
}

// Get recommendations based on decline type
export function getDeclineRecommendations(type: "hard" | "soft" | undefined): string[] {
  switch (type) {
    case "hard":
      return [
        "Do not retry the same payment method",
        "Request alternative payment method from customer",
        "Check if card details are correct",
        "Verify customer identity if fraud is suspected",
      ]
    case "soft":
      return [
        "Retry the transaction after a short delay",
        "Implement exponential backoff for retries",
        "Consider routing to alternative PSP",
        "Monitor system status and connectivity",
      ]
    default:
      return [
        "Analyze the specific decline reason",
        "Implement appropriate retry logic",
        "Consider manual review for unclear cases",
        "Update decline categorization rules",
      ]
  }
}

// Function to manually categorize common decline reasons
export function manuallyCategorizeDeclinesFromList(declineReasons: string[]): Record<string, "hard" | "soft"> {
  const categorization: Record<string, "hard" | "soft"> = {}

  declineReasons.forEach((reason) => {
    const category = categorizeDeclineReason(reason)
    if (category) {
      categorization[reason] = category
    } else {
      // Default to hard decline for uncategorized reasons
      categorization[reason] = "hard"
    }
  })

  return categorization
}
